### ISSUE TITLE
general - 3.0.0 Features

### ISSUE THREAD

**Issue by OMSmolina** [upmod/UPM#24]
List of first features.
- **Tools**
  - General
    - Camera: Based on BI Splendid Camera
    - 3 Spectator modes:
      - Free Cam
      - First Person
      - Third Person
  - Units / Groups
    - Lists for spectate:
  - Light / Heavy / Planes / Helis / Naval Vehicles
    - Lists for spectate:
  - Static Weapons
    - List for spectate
  - Environment
  - Performance
  - Settings
- **Setup**
  - Patrol any "marker-designated" area with any unit or group. 
    - DEFAULT: Randomly movements in designated area.
    - FORTIFY: Defensive positions in designated area. ( in that case some units may even occupy static weapons or stationary vehicles) 
  - Several independent marker areas (for different units) can be used on the same map. 
  - The start position can be are two types.
    - DEFAULT: Position where is located.
    - RANDOM: Position anywhere in the active area. (in that case some units may even end up on roofs)
  - You can create clones of a unit/group you placed in the active area.
  - You can disable follow enemies outside of his areamarker.
    - Levels: 0 to 5 (Lower number has tendency to stay in his areamarker)
- **AI Behaviour**
  - **General Commander (GC)**
    - Groups of AI fights together as an army, so they comunicate each other by radio the enemy known positions (Influenced by radio distance between each group).
    - GC can order to surrender entire side if army is seriously damaged.
  - **Patrols / Actions**
    - Adaptive conduct depends on terrain, patrol / action, fatigue, etc.
    - The units rest depending on the distance traveled. (Time and coverage affects if group is in patrol/action)
    - AI can follow enemies outside of his marker
    - Ai can cover tactically
    - FORTIFY: Rotative positions in town/village if it is big for group.
  - **Environment**
    - AI may even use empty vehicles for moving or to attack.
    - AI uses buildings to take defence position and patrol them when leader thinks than enemy is near or using it.
    - AI behaviour is affected by weather conditions.
  - **Units**
    - AI can use smoke grenades intelligently
    - Improved individual cover in 3-phases:
      -  1 Phase - reaction (0-3s):
      -   2 Phase - reaction (3-30s):
      -   3 Phase - reaction (30s>):
    - Improved driving skills
    - Improved navigation skills
    - Improved piloting skills

**Comment by Azroul13** [comment]
Maybe can be added:
- [x] NOFOLLOW: AI group will combat in his areamarker.

<strike>RESPAWN: When all units of group is dead, the group will respawn.</strike> (Backlog)

<strike>TEMPLATE: You can save the group composition to spawn it when you desire it. </strike> (Backlog)

**Comment by OMSmolina** [comment]
@Azroul13 Revised
