### ISSUE TITLE
UPM Slack (Chatroom) - Join Requests

### ISSUE THREAD

**Issue by OMSmolina** [upmod/UPM#50]
For anyone who wants to join the UPM slack (it's basically a chatroom type thing), please follow these instructions and I will send you an invite.

Please do one of the following:

Post your email as a comment to this issue
    OR
 Send me a PM on the BIS forums (http://forums.bistudio.com/member.php?217794-oscarmolinadev) [[please post here to let me know you have sent me a PM]]

It's open for everyone/anyone to join. :)

**Comment by kavinsky** [comment]
snip
[Done ~oscarmolinadev]
